#!/usr/bin/env bash

help(){
    cat<<__EOF__
    usage: m airdrop [ onlywifi | help ]

    Examples:
      m airdrop onlywifi YES      #  allow airdropping only via WIFI
      m airdrop onlywifi NO       #  allow airdropping via any network interface
__EOF__
}

onlywifi(){
    case $1 in
        [yY][eE][sS])
            defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true
            ;;
        [nN][oO])
            defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool false
            ;;
    esac

    value="$(_mcli_read_boolean "com.apple.NetworkBrowser" "BrowseAllInterfaces")"

    echo "Airdrop onlywifi: ${value}"
}

case $1 in
    help)
        help
        ;;
    onlywifi)
        shift
        onlywifi $@
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
