#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m appearance darkmode           [ YES | NO ]                # Whether to use dark versions of interface elements
      m appearance transparency       [ YES | NO ]                # Whether to allow the OS to make certain elements semi-transparent
      m appearance antialiasthreshold x                           # The threshold above which antialiasing is turned on
      m appearance sidebariconsize    [ small | medium | large ]  # The size of the icons in various window sidebars
      m appearance maincolor          [ blue | graphite ]         # The color used for the majority of the interface elements
      m appearance highlightcolor     [                           # The color used for highlights
                                        graphite  | cayenne    | asparagus  | clover    |
                                        teal      | midnight   | plum       | tin       |
                                        nickel    | mocha      | fern       | moss      |
                                        ocean     | eggplant   | maroon     | steel     |
                                        aluminum  | maraschino | lemon      | spring    |
                                        turquoise | blueberry  | magenta    | iron      |
                                        magnesium | tangerine  | lime       | seafoam   |
                                        aqua      | grape      | strawberry | tungsten  |
                                        silver    | salmon     | banana     | flora     |
                                        ice       | orchid     | bubblegum  | lead      |
                                        mercery   | cantaloupe | honeydew   | spindrift |
                                        sky       | lavender   | carnation  | licorice  |
                                        snow
                                      ]

    Examples:
      m appearance antialiasthreshold 8                           # Only a font size of 8pt or above will be anti-aliased
__EOF__
}

darkmode(){
    local choice="$(_mcli_convert_yes_no_to_boolean "$1")"
    local mode="$(if [[ "${choice}" == "true" ]]; then echo "Dark"; else echo "Light"; fi)"

    value="$(_mcli_defaults_string            "NSGlobalDomain" \
                                              "AppleInterfaceStyle" \
                                              "${mode}")"
    value="$(_mcli_defaults_yes_no_to_boolean "NSGlobalDomain" \
                                              "NSFullScreenDarkMenu" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

transparency(){
    value="$(_mcli_defaults_yes_no_to_inverted_boolean "com.apple.universalaccess" \
                                                       "reduceTransparency" \
                                                       "$1")"

    echo "${command} ${subcommand}: ${value}"
}

antialiasthreshold(){
    value="$(_mcli_defaults_number "NSGlobalDomain" \
                                   "AppleAntiAliasingThreshold" \
                                   "$1")"

    echo "${command} ${subcommand}: ${value}"
}

sidebariconsize(){
    local size

    case $1 in
        small)
            size="1"
            ;;
        medium)
            size="2"
            ;;
        large)
            size="3"
            ;;
    esac

    value="$(_mcli_defaults_number "NSGlobalDomain" \
                                   "NSTableViewDefaultSizeMode" \
                                   "${size}")"
    value="$(_mcli_defaults_number "NSGlobalDomain" \
                                   "NSNavPanelIconViewIconSizeForOpenMode" \
                                   "${size}")"

    echo "${command} ${subcommand}: ${value}"
}

maincolor(){
    local color

    case $1 in
        blue)
            color="1"
            ;;
        graphite)
            color="6"
            ;;
    esac

    value="$(_mcli_defaults_number "NSGlobalDomain" \
                                   "AppleAquaColorVariant" \
                                   "${color}")"

    echo "${command} ${subcommand}: ${value}"
}

highlightcolor(){
    local color

    # Highlight colors (from the crayons picker)
    case $1 in
        graphite)
            color="0.780400 0.815700 0.858800";;
        cayenne)
            color="0.501961 0.000000 0.000000";;
        asparagus)
            color="0.501961 0.501961 0.000000";;
        clover)
            color="0.000000 0.501961 0.000000";;
        teal)
            color="0.000000 0.501961 0.501961";;
        midnight)
            color="0.000000 0.000000 0.501961";;
        plum)
            color="0.501961 0.000000 0.501961";;
        tin)
            color="0.498039 0.498039 0.498039";;
        nickel)
            color="0.501961 0.501961 0.501961";;
        mocha)
            color="0.501961 0.250980 0.000000";;
        fern)
            color="0.250980 0.501961 0.000000";;
        moss)
            color="0.000000 0.501961 0.250980";;
        ocean)
            color="0.000000 0.250980 0.501961";;
        eggplant)
            color="0.250980 0.000000 0.501961";;
        maroon)
            color="0.501961 0.000000 0.250980";;
        steel)
            color="0.400000 0.400000 0.400000";;
        aluminum)
            color="0.600000 0.600000 0.600000";;
        maraschino)
            color="1.000000 0.000000 0.000000";;
        lemon)
            color="1.000000 1.000000 0.000000";;
        spring)
            color="0.000000 1.000000 0.000000";;
        turquoise)
            color="0.000000 1.000000 1.000000";;
        blueberry)
            color="0.000000 0.000000 1.000000";;
        magenta)
            color="1.000000 0.000000 1.000000";;
        iron)
            color="0.298039 0.298039 0.298039";;
        magnesium)
            color="0.701961 0.701961 0.701961";;
        tangerine)
            color="1.000000 0.501961 0.000000";;
        lime)
            color="0.501961 1.000000 0.000000";;
        seafoam)
            color="0.000000 1.000000 0.501961";;
        aqua)
            color="0.000000 0.501961 1.000000";;
        grape)
            color="0.501961 0.000000 1.000000";;
        strawberry)
            color="1.000000 0.000000 0.501961";;
        tungsten)
            color="0.200000 0.200000 0.200000";;
        silver)
            color="0.800000 0.800000 0.800000";;
        salmon)
            color="1.000000 0.400000 0.400000";;
        banana)
            color="1.000000 1.000000 0.400000";;
        flora)
            color="0.400000 1.000000 0.400000";;
        ice)
            color="0.400000 1.000000 1.000000";;
        orchid)
            color="0.400000 0.400000 1.000000";;
        bubblegum)
            color="1.000000 0.400000 1.000000";;
        lead)
            color="0.0980392 0.0980392 0.0980392";;
        mercery)
            color="0.901961 0.901961 0.901961";;
        cantaloupe)
            color="1.000000 0.800000 0.400000";;
        honeydew)
            color="0.800000 1.000000 0.400000";;
        spindrift)
            color="0.400000 1.000000 0.800000";;
        sky)
            color="0.400000 0.800000 1.000000";;
        lavender)
            color="0.800000 0.400000 1.000000";;
        carnation)
            color="1.000000 0.435294 0.811765";;
        licorice)
            color="0.000000 0.000000 0.000000";;
        snow)
            color="1.000000 1.000000 1.000000";;
    esac

    value="$(_mcli_defaults_string            "NSGlobalDomain" \
                                              "AppleHighlightColor" \
                                              "${color}")"
    value="$(_mcli_defaults_string            "com.apple.systempreferences" \
                                              "AppleOtherHighlightColor" \
                                              "${color}")"

    echo "${command} ${subcommand}: ${value}"
}

case "${subcommand}" in
    help)
        help
        ;;
    darkmode)
        darkmode "$@"
        ;;
    transparency)
        transparency "$@"
        ;;
    antialiasthreshold)
        antialiasthreshold "$@"
        ;;
    sidebariconsize)
        sidebariconsize "$@"
        ;;
    maincolor)
        maincolor "$@"
        ;;
    highlightcolor)
        highlightcolor "$@"
        ;;
    *)
        help
        ;;
esac
