#!/usr/bin/env bash

help(){
    cat<<__EOF__
Usage: m battery [OPTIONS]

Description: battery management commands

Options:
  --help        Show this help message
  --status      Show the current battery status
__EOF__
}

battery_status(){
    pmset -g batt
}

case $1 in
    --help)
        help ;;
    --status)
        battery_status ;;
    *)
        help && exit 1 ;;
esac
