#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m datetime 24hourclock    [ YES | NO ] # Whether to show the time using a 24 hour clock
      m datetime usentpserver   [ YES | NO ] # Whether the current date time can be set via NTP
      m datetime ntpserver      hostname     # The NTP server to use to set the time
      m datetime international  [ YES ]      # Sets the date/time formats to the international standard
      m datetime menubarformat  format       # Sets format of the clock in the menu bar
__EOF__
}

24hourclock(){
    local choice="$(_mcli_convert_yes_no_to_boolean "$1")"
    local hour_format="$(if [[ "${choice}" == "true" ]]; then echo "H"; else echo "h"; fi)"

    defaults delete NSGlobalDomain AppleICUTimeFormatStrings &> /dev/null

    defaults write NSGlobalDomain AppleICUTimeFormatStrings -dict-add "1" "${hour_format}:mm"
    defaults write NSGlobalDomain AppleICUTimeFormatStrings -dict-add "2" "${hour_format}:mm:ss"
    defaults write NSGlobalDomain AppleICUTimeFormatStrings -dict-add "3" "${hour_format}:mm:ss z"
    defaults write NSGlobalDomain AppleICUTimeFormatStrings -dict-add "4" "${hour_format}:mm:ss zzzz"

    value="$(_mcli_defaults_yes_no_to_boolean "NSGlobalDomain" \
                                              "AppleICUForce24HourTime" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

usentpserver(){
    local choice="$(_mcli_convert_yes_no_to_on_off "$1")"

    sudo sh -c "/usr/sbin/systemsetup -setusingnetworktime ${choice} &> /dev/null"
}

ntpserver(){
    sudo sh -c "/usr/sbin/systemsetup -setnetworktimeserver '$1' &> /dev/null"
}

international() {
    defaults delete NSGlobalDomain AppleICUDateFormatStrings > /dev/null 2&>1

    defaults write NSGlobalDomain AppleICUDateFormatStrings -dict-add "1" "yyyy-MM-dd"
    defaults write NSGlobalDomain AppleICUDateFormatStrings -dict-add "2" "yyyy MMM d"
    defaults write NSGlobalDomain AppleICUDateFormatStrings -dict-add "3" "yyyy MMMM d"
    defaults write NSGlobalDomain AppleICUDateFormatStrings -dict-add "4" "EEEE yyyy MMMM d"
}

menubarformat() {
    defaults write com.apple.menuextra.clock DateFormat -string "$1"
}

case "${subcommand}" in
    help)
        help
        ;;
    24hourclock)
        24hourclock "$@"
        ;;
    usentpserver)
        usentpserver "$@"
        ;;
    ntpserver)
        ntpserver "$@"
        ;;
    international)
        international "$@"
        ;;
    menubarformat)
        menubarformat "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
