#!/usr/bin/env bash

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m dialogs autoexpand  [ YES | NO ]  # Whether print, save and other dialogs auto-expand
__EOF__
}

autoexpand(){
    value="$(_mcli_defaults_yes_no_to_boolean "NSGlobalDomain" \
                                              "NSNavPanelExpandedStateForSaveMode" \
                                              "$1")"
    value="$(_mcli_defaults_yes_no_to_boolean "NSGlobalDomain" \
                                              "NSNavPanelExpandedStateForSaveMode2" \
                                              "$1")"
    value="$(_mcli_defaults_yes_no_to_boolean "NSGlobalDomain" \
                                              "PMPrintingExpandedStateForPrint" \
                                              "$1")"
    value="$(_mcli_defaults_yes_no_to_boolean "NSGlobalDomain" \
                                              "PMPrintingExpandedStateForPrint2" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

case "${subcommand}" in
    help)
        help
        ;;
    autoexpand)
        autoexpand "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
