#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    usage: m diskutility [ advancedoptions | showhiddenpartitions | showunsupportednetworks | help ]

    Examples:
      m diskutility advancedoptions         [ YES | NO ]  # Whether to enable advanced disk utility options
      m diskutility showhiddenpartitions    [ YES | NO ]  # Whether to show hidden partitions
      m diskutility showunsupportednetworks [ YES | NO ]  # Whether to show unsupported networks
__EOF__
}

advancedoptions(){
    value="$(_mcli_defaults_yes_no_to_integer "com.apple.DiskUtility" \
                                              "advanced-image-options" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

showhiddenpartitions(){
    value="$(_mcli_defaults_yes_no_to_integer "com.apple.DiskUtility" \
                                              "DUShowEveryPartition" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

showunsupportednetworks(){
    value="$(_mcli_defaults_yes_no_to_integer "com.apple.DiskUtility" \
                                              "DUShowUnsupportedNetworks" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

case "${subcommand}" in
    help)
        help
        ;;
    advancedoptions)
        advancedoptions "$@"
        ;;
    showhiddenpartitions)
        showhiddenpartitions "$@"
        ;;
    showunsupportednetworks)
        showunsupportednetworks "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
