#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare path_to_plist="/Library/Preferences/com.apple.iokit.AmbientLightSensor"
declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m display status                       # status of displays
      m display autobrightness [ YES | NO ]  # whether to enable the ambient light sensor to automatically darken/brighten the screen
__EOF__
}

display_status(){
    system_profiler SPDisplaysDataType
}

autobrightness() {
    value="$(_mcli_defaults_yes_no_to_integer "${path_to_plist}" \
                                              "Automatic Display Enabled" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

case "${subcommand}" in
    help)
        help
        ;;
    status)
        display_status
        ;;
    autobrightness)
        autobrightness "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
