#!/usr/bin/env bash

help(){
    cat<<__EOF__
Usage: m display [OPTIONS]

Description: Manage display settings on macOS

Options:
  --help              Show this help message
  --status            Show current display status
  --up [COUNT]        Increase display brightness (default COUNT=1)
  --down [COUNT]      Decrease display brightness (default COUNT=1)


__EOF__
}

display_status(){
    system_profiler SPDisplaysDataType
}


send_brightness_key(){
    local key_code="$1"
    local count="${2:-1}"

    if [ -z "${key_code}" ]; then
        help && exit 1
    fi

    if ! [[ "${count}" =~ ^[0-9]+$ ]] || [ "${count}" -le 0 ]; then
        help && exit 1
    fi

    local repeats=$((count * 2))
    osascript -e "repeat ${repeats} times" -e "tell application \"System Events\" to key code ${key_code}" -e 'delay 0.3' -e 'end repeat'
}

turn_up(){
    local count="${1:-1}"
    send_brightness_key 144 "${count}"
}

turn_down(){
    local count="${1:-1}"
    send_brightness_key 145 "${count}"
}

case $1 in
    --help)
        help
        ;;
    --status)
        display_status
        ;;
    --up)
        turn_up "$2"
        ;;
    --down)
        turn_down "$2"
        ;;
    *)
        help && exit 1
        ;;
esac
