#!/bin/bash

help(){
    cat<<__EOF__
    usage:  m dns [ flush | help ]

    Examples:
      m dns flush       # flushes local DNS
__EOF__
}


flushdns(){
    product_version=$(sw_vers -productVersion)
    semver=( ${product_version//./ } )
    major="${semver[0]}"
    minor="${semver[1]}"
    patch="${semver[2]}"
    echo "Flushing dns..."
    if [[ ${patch} =~ [0-3] && ${minor} -eq 10 && ${major} -eq 10 ]]; then
        # 10.10.0 - 10.10.3
        sudo discoveryutil mdnsflushcache
    elif [[ ${minor} -eq 6 && ${major} -eq 10 ]]; then
        # 10.6.x
        sudo dscacheutil -flushcache
    elif [[ ${major} -eq 10 ]]; then
        sudo killall -HUP mDNSResponder
    fi
}


case $1 in
    help)
        help
        ;;
    flush)
        flushdns
        ;;
    *)
        help
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
