#!/usr/bin/env bash

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    usage: m filevault [ status | enable | disable | standbykey | help ]

    Examples:
      m filevault status                    # FileVault Status
      m filevault enable                    # Enable FileVault
      m filevault disable                   # Disable FileVault
      m filevault standbykey [ YES | NO ]   # Whether to keep the filevault key in memory during sleep
__EOF__
}

standbykey(){
    choice="$(_mcli_convert_yes_no_to_integer "$1")"

    sudo pmset -a destroyfvkeyonstandby "${choice}"
}

case "${subcommand}" in
    help)
        help
        ;;
    status)
        sudo fdesetup status "$@"
        ;;
    enable)
        sudo fdesetup enable "$@"
        ;;
    disable)
        sudo fdesetup disable "$@"
        ;;
    standbykey)
        standbykey "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
