#!/bin/sh

# TODO: add more functionalities

help(){
    cat<<__EOF__
    usage: m finder [ showhiddenfiles | showfileextensions | showdesktop | help ]

    Examples:
      m finder showhiddenfiles           # get the current status
      m finder showhiddenfiles YES       # show hidden files
      m finder showhiddenfiles NO        # no show hidden files
      m finder showextensions            # get the current status
      m finder showextensions YES        # show all file extensions
      m finder showextensions NO         # don't show all file extensions
      m finder showdesktop               # get the current desktop status
      m finder showdesktop YES           # enable the desktop
      m finder showdesktop NO            # disable the desktop
__EOF__
}

hidden_files(){
    case $1 in
        [yY][eE][sS])
            echo "Show Hidden files: YES"
            defaults write com.apple.finder AppleShowAllFiles YES
            ;;
        [nN][oO])
            echo "Show Hidden files: NO"
            defaults write com.apple.finder AppleShowAllFiles NO
            ;;
        *)
            echo "Show Hidden files: $(defaults read com.apple.finder AppleShowAllFiles)"
            exit 1
            ;;
    esac
    killall Finder
}

file_extensions(){
    case $1 in
        [yY][eE][sS])
            echo "Show Hidden files: YES"
            defaults write NSGlobalDomain AppleShowAllExtensions YES
            ;;
        [nN][oO])
            echo "Show Hidden files: NO"
            defaults write NSGlobalDomain AppleShowAllExtensions NO
            ;;
        *)
            echo "Show All File Extensions: $(defaults read NSGlobalDomain AppleShowAllExtensions)"
            exit 1
            ;;
    esac
    killall Finder
}

desktop(){
    case $1 in
        [yY][eE][sS])
            echo "Enable desktop: YES"
            defaults write com.apple.finder CreateDesktop -bool TRUE
            ;;
        [nN][oO])
            echo "Enable desktop: NO"
            defaults write com.apple.finder CreateDesktop -bool FALSE
            ;;
        *)
            DESKTOP_STATUS_NUM=$(defaults read com.apple.finder CreateDesktop 2>/dev/null)
            if [ "$DESKTOP_STATUS_NUM" -eq 0 ] ; then
              DESKTOP_STATUS="disabled"
            else
              DESKTOP_STATUS="enabled"
            fi
            echo "Desktop is: $DESKTOP_STATUS"
            ;;
    esac
    killall Finder
}

case $1 in
    help)
        help
        ;;
    showhiddenfiles)
        shift
        hidden_files $@
        ;;
    showextensions)
        shift
        file_extensions $@
        ;;
    showdesktop)
        shift
        desktop $@
        ;;
    *)
        help
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
