#!/usr/bin/env bash

# TODO: add more functionalities

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    usage: m finder [ showhiddenfiles | showfileextensions | showdesktop | help ]

    Examples:
      m finder showhiddenfiles              # get the current status
      m finder showhiddenfiles YES          # show hidden files
      m finder showhiddenfiles NO           # don't show hidden files

      m finder showextensions               # get the current status
      m finder showextensions YES           # show all file extensions
      m finder showextensions NO            # don't show all file extensions

      m finder showdesktop                  # get the current desktop status
      m finder showdesktop YES              # enable the desktop
      m finder showdesktop NO               # disable the desktop

      m finder remotedsstore [ YES | NO ]   # whether to allow dsstore files to be created on remote volumes
__EOF__
}

hidden_files(){
    value="$(_mcli_defaults_yes_no_to_boolean "com.apple.finder" \
                                              "AppleShowAllFiles" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

file_extensions(){
    value="$(_mcli_defaults_yes_no_to_boolean "NSGlobalDomain" \
                                              "AppleShowAllExtensions" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

desktop(){
    value="$(_mcli_defaults_yes_no_to_boolean "com.apple.finder" \
                                              "CreateDesktop" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

remotedsstore(){
    local choice="$(_mcli_defaults_yes_no_to_boolean "$1")"

    if [[ "${choice}" == "true" ]]; then
        defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
        defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
    else
        defaults delete com.apple.desktopservices DSDontWriteNetworkStores
        defaults delete com.apple.desktopservices DSDontWriteUSBStores
    fi
}

case "${subcommand}" in
    help)
        help
        ;;
    showhiddenfiles)
        hidden_files "$@"
        ;;
    showextensions)
        file_extensions "$@"
        ;;
    showdesktop)
        desktop "$@"
        ;;
    remotedsstore)
        remotedsstore "$@"
        ;;
    *)
        help
        ;;
esac

[ -n "${subcommand}" ] && [ -n "$1" ] && killall Finder

# vim: ts=4 sw=4 softtabstop=4 expandtab
