#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m firewall status                            # Show status
      m firewall enable                            # Enable firewall
      m firewall disable                           # Disable firewall
      m firewall list                              # List applications handled by firewall
      m firewall autoallowsignedapps  [ YES | NO ] # Whether to allow signed applications automatically
      m firewall blockall             [ YES | NO ] # Whether to block all incoming connections
      m firewall logging              [ YES | NO ] # Whether to enable firewall logging
      m firewall stealth              [ YES | NO ] # Whether to respond to pings
      m firewall add /path/to/file                 # Add app to firewall
      m firewall remove /path/to/file              # Remove app from firewall
__EOF__
}

case "${subcommand}" in
    help)
        help
        ;;
    status)
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate
        ;;
    enable)
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on
        ;;
    disable)
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate off
        ;;
    autoallowsignedapps)
        choice="$(_mcli_convert_yes_no_to_on_off "$1")"

        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setallowsigned "${choice}"
        ;;
    blockall)
        choice="$(_mcli_convert_yes_no_to_on_off "$1")"

        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setblockall "${choice}"
        ;;
    logging)
        choice="$(_mcli_convert_yes_no_to_on_off "$1")"

        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setloggingmode "${choice}"
        ;;
    stealth)
        choice="$(_mcli_convert_yes_no_to_on_off "$1")"

        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setstealthmode "${choice}"
        ;;
    list)
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --list
        ;;
    add)
        [ -z "$2" ] && help && exit 1
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --add "$2"
        ;;
    remove)
        [ -z "$2" ] && help && exit 1
        sudo /usr/libexec/ApplicationFirewall/socketfilterfw --remove "$2"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
