#!/usr/bin/env bash


help(){
    cat<<__EOF__
    Usage:
      m hostname                # get the current hostname information (computername, hostname, localhostname and netbiosname)
      m hostname <newhostname>  # set a new hostname (computername, hostname, localhostname, netbiosname)
__EOF__
}


show_hostname(){
    scutil --get ComputerName | awk '{print "ComputerName: ", $1}'
    scutil --get HostName | awk '{print "HostName: ", $1}'
    scutil --get LocalHostName | awk '{print "LocalHostName: ", $1}'
    defaults read /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName | awk '{print "NetBIOSName: " $1}'
}


set_hostname(){
    local hostname="$1"

    echo "Changing hostname to: ${hostname}"

    sudo sh -c "hostname '${hostname}'"
    sudo sh -c "scutil --set ComputerName '${hostname}'"
    sudo sh -c "scutil --set HostName '${hostname}'"
    sudo sh -c "scutil --set LocalHostName '${hostname}'"
    sudo sh -c "/usr/sbin/systemsetup -setcomputername '${hostname}' &> /dev/null"
    sudo sh -c "/usr/sbin/systemsetup -setlocalsubnetname '${hostname}' &> /dev/null"

    sudo sh -c "defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string '${hostname}'"
    sudo sh -c "defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server ServerDescription -string '${hostname}'"
}


case $1 in
    help)
        help
        ;;
    *)
        if [ -z "$1" ]; then
            show_hostname
        else
            set_hostname $1
        fi
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
