#!/usr/bin/env bash


help(){
    cat<<__EOF__
    usage: m info [ help ]

    Examples:
      m info        #  print Mac OS X operating system version information
__EOF__
}

case $1 in
    help)
        help
        ;;
    *)
        sw_vers
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
