#!/usr/bin/env bash

help(){
    cat<<__EOF__
Usage: m info [OPTIONS]

Description: Print macOS operating system version information.

Options:
  --help  Show this help message and exit.
__EOF__
}

case $1 in
    --help)
        help
        ;;
    *)
        sw_vers
        ;;
esac
