#!/usr/bin/env bash

help () {
    cat<<__EOF__
    usage: m itunes [ status | play | pause | next | prev | mute | unmute | vol up | vol down | vol # | stop | quit | help ]

    Examples:
      m itunes status       # Show status
      m itunes play         # Play track
      m itunes pause        # Pause track
      m itunes next         # Play next track
      m itunes prev         # Play previous track
      m itunes mute         # Mute iTunes
      m itunes unmute       # Unmute iTunes
      m itunes vol up       # Volume Up
      m itunes vol down     # Volume Down
      m itunes vol #        # Set volume level
      m itunes stop         # Stop track
      m itunes quit         # Quit iTunes
__EOF__
}

case $1 in
    help)
        help
        ;;
    status)
        state=`osascript -e 'tell application "iTunes" to player state as string'`
        echo "iTunes is currently $state."
        if [ $state = "playing" ]; then
            artist=`osascript -e 'tell application "iTunes" to artist of current track as string'`
            track=`osascript -e 'tell application "iTunes" to name of current track as string'`
            echo "Current track $artist:  $track"
        fi
        ;;
    play)
        osascript -e 'tell application "iTunes" to play'
        ;;
    pause)
        osascript -e 'tell application "iTunes" to pause'
        ;;
    next)
        osascript -e 'tell application "iTunes" to next track'
        ;;
    prev)
        osascript -e 'tell application "iTunes" to previous track'
        ;;
    mute)
        osascript -e 'tell application "iTunes" to set mute to true'
        ;;
    unmute)
        osascript -e 'tell application "iTunes" to set mute to false'
        ;;
    vol)
        vol=`osascript -e 'tell application "iTunes" to sound volume as integer'`
        if [ $2 = "up" ]; then
            newvol=$(( vol+10 ))
        fi

        if [ $2 = "down" ]; then
            newvol=$(( vol-10 ))
        fi

        if [ $2 -gt 0 ]; then
            newvol=$2
        fi
        osascript -e "tell application \"iTunes\" to set sound volume to $newvol"
        ;;
    stop)
        osascript -e 'tell application "iTunes" to stop'
        ;;
    quit)
        osascript -e 'tell application "iTunes" to quit'
        ;;
    *)
        help
        ;;
esac