#!/usr/bin/env bash

MAC_MAJOR=$(/usr/bin/sw_vers -productVersion | /usr/bin/awk -F. '{print $1}')
MAC_MINOR=$(/usr/bin/sw_vers -productVersion | /usr/bin/awk -F. '{print $2}')

music_cmd="iTunes"
# check if >= Catalina (10.15)
# iTunes was renamed to Music
if [ "${MAC_MAJOR}" -gt 10 ] || { [ "${MAC_MAJOR}" -eq 10 ] && [ "${MAC_MINOR}" -ge 15 ]; }; then
  music_cmd="Music"
fi

help () {
    cat<<__EOF__
Usage: m ${music_cmd} [OPTION] [ARGUMENTS]

Description: Control ${music_cmd} via command line

Options:
  --help            Show this help message
  --status          Show current status
  --play            Play current track
  --playpause       Play/pause current track
  --toggle          Toggle play/pause current track
  --stop            Stop current track
  --pause           Pause current track
  --next            Play next track
  --prev            Play previous track
  --mute            Mute ${music_cmd}
  --unmute          Unmute ${music_cmd}
  --vol LEVEL       Set application volume to LEVEL (0-100)
  --quit            Quit ${music_cmd}
__EOF__
}

show_status(){
    state=`osascript -e "tell application \"${music_cmd}\" to player state as string"`
    echo "${music_cmd} is currently $state."
    if [ $state = "playing" ]; then
        artist=`osascript -e "tell application \"${music_cmd}\" to artist of current track as string"`
        track=`osascript -e "tell application \"${music_cmd}\" to name of current track as string"`
        echo "Current track $artist:  $track"
    fi
}

set_volume(){
    local value="${1}"
    local vol=`osascript -e "tell application \"${music_cmd}\" to sound volume as integer"`

    case "${value}" in
        [0-9]*)
            newvol="${1}"
            ;;
        *)
            help  && exit 1
            ;;
    esac
    osascript -e "tell application \"${music_cmd}\" to set sound volume to ${newvol}"
}

case $1 in
    --help|help|-h)
        help
        ;;
    --status|status)
        show_status
        ;;
    --play|play)
        osascript -e "tell application \"${music_cmd}\" to play"
        ;;
    --playpause|--toggle|playpause|toggle|play/pause)
        osascript -e "tell application \"${music_cmd}\" to playpause"
        ;;
    --pause|pause)
        osascript -e "tell application \"${music_cmd}\" to pause"
        ;;
    --next|next)
        osascript -e "tell application \"${music_cmd}\" to next track"
        ;;
    --prev|prev)
        osascript -e "tell application \"${music_cmd}\" to previous track"
        ;;
    --mute|mute)
        osascript -e "tell application \"${music_cmd}\" to set mute to true"
        ;;
    --unmute|unmute)
        osascript -e "tell application \"${music_cmd}\" to set mute to false"
        ;;
    --vol|vol)
        shift
        set_volume "$@"
        ;;
    --stop|stop)
        osascript -e "tell application \"${music_cmd}\" to stop"
        ;;
    --quit|quit)
        osascript -e "tell application \"${music_cmd}\" to quit"
        ;;
    *)
        help
        ;;
esac
