#!/usr/bin/env bash

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    usage: m launchpad [ prune | help ]

    Examples:
      m launchpad prune   # Remove all items from launchpad
__EOF__
}

prune(){
    find "/Users/$(whoami)/Library/Application Support/Dock" -name "*-*.db" -maxdepth 1 -delete
}

case "${subcommand}" in
    help)
        help
        ;;
    prune)
        prune
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
