#!/usr/bin/env bash

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    usage: m location [ prune | help ]

    Examples:
      m location enable    # Enable the location service
      m location diable    # Disable the location service
__EOF__
}

_mcli_enable_location_service(){
    local loaded="$(_mcli_convert_yes_no_to_load_unload "$1")"

    value="$(_mcli_defaults_yes_no_to_inverted_boolean "com.apple.MCX" \
                                                       "DisableLocationServices" \
                                                       "$1")"

    value="$(_mcli_defaults_yes_no_to_boolean "com.apple.locationd" \
                                              "LocationServicesEnabled" \
                                              "$1")"

    sudo sh -c "launchctl ${loaded} -w /System/Library/LaunchDaemons/com.apple.locationd.plist 2> /dev/null"

    echo "${command} ${subcommand}: ${value}"
}

enable(){
    _mcli_enable_location_service "true"
}

disable(){
    _mcli_enable_location_service "false"
}

case "${subcommand}" in
    help)
        help
        ;;
    enable)
        enable
        ;;
    disable)
        disable
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
