#!/usr/bin/env bash

spacing="            "

help() {
    cat <<__EOF__
    usage: m localhost [ help ]

    Examples:
      m localhost ls                              # list current records in localhost
      m localhost add 127.0.0.1 webpage.local     # add a new host to the localhost file
      m localhost remove webpage.local            # remove a host from the localhost file
__EOF__
}

case $1 in
help)
    help
    ;;
ls)
    sudo echo "IP $spacing DOMAIN" && cat /etc/hosts | grep -v "#" | grep -v "^$"
    ;;
add)
    [ -z "$2" ] && [ -z "$3"] && help && exit 1
    sudo echo "$2   $3" | sudo /usr/bin/tee -a /etc/hosts
    sudo m dns flush
    ;;
remove)
    [ -z "$2" ] && help && exit 1
    sudo /usr/bin/sed -i '' "/$2/d" /etc/hosts
    sudo m dns flush
    ;;
*)
    help
    ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
