#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m locale language <language_code>      # Specify the language to use (eg en_US)
      m locale unit     [ metric | english ] # Specify the measurement unit
__EOF__
}

language(){
    defaults write NSGlobalDomain AppleLocale "$1"
}

unit(){
    local unit="$(if [[ "$1" == "metric" ]]; then echo "Centimeters"; else echo "Inches"; fi)"
    local metric="$(if [[ "$1" == "metric" ]]; then echo "true"; else echo "false"; fi)"

    defaults write NSGlobalDomain AppleMeasurementUnits -string  "${unit}"
    defaults write NSGlobalDomain AppleMetricUnits      -boolean "${metric}"
}

case "${subcommand}" in
    help)
        help
        ;;
    language)
        language $@
        ;;
    unit)
        unit $@
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
