#!/bin/sh

help(){
    cat<<__EOF__
    usage:  m lock [ help ]

    Examples:
      m lock      # lock session
__EOF__
}

lock(){
    /System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend
}

case $1 in
    help)
        help
        ;;
    *)
        lock
        ;;
esac

# vim: set ts=4 sw=4 softtabstop=4 expandtab
