#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m loginitems add <path_to_app> [ YES | NO ]  # Add a login item.  Optionally specifying wheither it should be hidden.
__EOF__
}

add(){
    local application_path="$1"
    local hidden="$(_mcli_convert_yes_no_to_boolean "$2")"

    osascript -e "tell application \"System Events\" to make login item at end with properties {path:\"${application_path}\", hidden:${hidden}}" &> /dev/null
}

case "${subcommand}" in
    help)
        help
        ;;
    add)
        add "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
