#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    usage: m menubar [ autohide | airplay | help ]

    Examples:
      m menubar autohide [ YES | NO ]   # Whether to autohide the menu bar
      m menubar airplay  [ YES | NO ]   # Whether to show the airplay options in the menu bar

__EOF__
}

autohide() {
    value="$(_mcli_defaults_yes_no_to_boolean "NSGlobalDomain" \
                                              "_HIHideMenuBar" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

airplay() {
    value="$(_mcli_defaults_yes_no_to_boolean "com.apple.airplay" \
                                              "showInMenuBarIfPresent" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

case "${subcommand}" in
    help)
        help
        ;;
    autohide)
        autohide "$@"
        ;;
    airplay)
        airplay "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
