#!/usr/bin/env bash


help(){
    cat<<__EOF__
    Usage:
      m nosleep until <number_of_seconds>   # no sleep until number of seconds elaspes
      m nosleep until <script_path>         # no sleep until the script ends
      m nosleep until pid <pid_id>          # no sleep until the process id ends

    Examples:
      m nosleep until 3600
      m nosleep until my_script.sh
      m nosleep until pid 64377
__EOF__
}


nosleep_until(){
    case $1 in
        [0-9]*)
            caffeinate -u -t "${1}"
            ;;
        pid)
            shift # remove "pid" arg
            [ "$#" -lt 1 ] && help && exit 1
            caffeinate -w "${1}"
            ;;
        *)
            #caffeinate "$@"
            help && exit 1
            ;;
    esac

}



case $1 in
    help)
        help
        ;;
    until)
        shift  # remove "until" arg
        nosleep_until $@
        ;;

    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
