#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m notification enable                   # enable the notification center
      m notification disable                  # disable the notification center
      m notification bannertime x             # change the time that banners stay on the screen for
__EOF__
}

enable(){
  showcenter "YES"
}

disable(){
  showcenter "NO"
}

showcenter(){
    [ -z "$1" ] && help && return

    local choice="$(_mcli_convert_yes_no_to_load_unload "$1")"

    launchctl "${choice}" -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist

    value="$(_mcli_convert_exit_status_to_enabled_disabled "ps -A | grep apsd | grep -v grep")"

    echo "${command} ${subcommand}: ${value}"
}

bannertime(){
    value="$(_mcli_defaults_string "com.apple.notificationcenterui" \
                                   "bannerTime" \
                                   "$1")"

    echo "${command} ${subcommand}: ${value}"
}

case "${subcommand}" in
    help)
        help
        ;;
    showcenter)
        showcenter "$@"
        ;;
    enable)
        enable "$@"
        ;;
    disable)
        disable "$@"
        ;;
    bannertime)
        bannertime "$@"
        ;;
    *)
        help
        ;;
esac

[ -n "${subcommand}" ] && [ -n "$1" ] && killall NotificationCenter && echo "Restart your computer for this to take effect"

# vim: ts=4 sw=4 softtabstop=4 expandtab
