#!/usr/bin/env bash

help() {
    cat <<__EOF__
    usage: m powermode [ battery | ac | auto | low | high | help ]

    Examples:
      m powermode                             # get the current power mode
      m powermode battery                     # get the power mode for battery
      m powermode ac                          # get the power mode for ac

      m powermode auto | low | high           # set the current power mode
      m powermode battery auto | low | high   # set the power mode for battery
      m powermode ac auto | low | high        # set the power mode for ac

__EOF__
}

get_powermode() {
    # convert to words
    case $1 in
    0)
        powermode="auto"
        ;;
    1)
        powermode="low"
        ;;
    2)
        powermode="high"
        ;;
    *)
        echo "We can't read the power mode" && exit 1
        ;;
    esac
    echo "Power mode: $powermode"
}

powermode() {
    case $1 in
    ac)
        case $2 in
        auto)
            sudo pmset -c powermode 0
            ;;
        low)
            sudo pmset -c powermode 1
            ;;
        high)
            sudo pmset -c powermode 2
            ;;
        "")
            get_powermode "$(pmset -g custom | grep -A5000 -m1 -e 'AC Power' | grep -i 'powermode' -m1 | awk '{print $2}')"
            ;;
        *)
            help
            ;;
        esac
        ;;
    battery)
        case $2 in
        auto)
            sudo pmset -b powermode 0
            ;;
        low)
            sudo pmset -b powermode 1
            ;;
        high)
            sudo pmset -b powermode 2
            ;;
        "")
            get_powermode "$(pmset -g custom | grep -A5000 -m1 -e 'Battery Power' | grep -i 'powermode' -m1 | awk '{print $2}')"
            ;;
        *)
            help
            ;;
        esac
        ;;
    "" | auto | low | high)
        # no ac/battery specified
        case $1 in
        auto)
            sudo pmset -a powermode 0
            ;;
        low)
            sudo pmset -a powermode 1
            ;;
        high)
            sudo pmset -a powermode 2
            ;;
        "")
            get_powermode "$(pmset -g live | grep -i 'powermode' | awk '{print $2}')"
            ;;
        *)
            help
            ;;
        esac
        ;;
    *)
        help
        ;;
    esac
}

case $1 in
help)
    help
    ;;
# powermode)
#     shift
#     powermode "$@"
#     ;;
*)
    # help
    powermode "$@"
    ;;
esac
