#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m printer settings                        # Printer settings
      m printer name                            # Display printer names on system
      m printer queue                           # Display items in printer queue on system
      m printer drivers                         # Display all printer drivers
      m printer web                             # Enable and show web interface
      m printer quitwhenfinished [ YES | NO ]   # whether the print dialog should be closed when printing is finished

__EOF__
}

quitwhenfinished(){
    value="$(_mcli_defaults_yes_no_to_boolean "com.apple.print.PrintingPrefs" \
                                              "Quit When Finished" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

case "${subcommand}" in
    help)
        help
        ;;
    settings)
        /usr/bin/lpoptions -l
        ;;
    name)
        lpstat -p | awk '{print $2}'
        ;;
    queue)
        lpstat -p | awk '{print $2}' | xargs -n1 lpq -P
        ;;
    drivers)
        lpinfo -m
        ;;
    web)
        cupsctl WebInterface=yes && open http://localhost:631/printers
        ;;
    quitwhenfinished)
        quitwhenfinished "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
