#!/usr/bin/env bash


help(){
    cat<<__EOF__
    usage: m screensaver [ status | askforpassword | help ]

    Examples:
      m screensaver                         # launch screensaver

      m screensaver status                  #  get the current status
      m screensaver askforpassword          #  get password requirement to unlock
      m screensaver askforpassword YES      #  enable password requirement to unlock
      m screensaver askforpassword NO       #  disable password requirement to unlock
__EOF__
}

askforpassword(){
    case $1 in
        [yY][eE][sS])
            defaults write com.apple.screensaver askForPassword -int 1
            echo "Screensaver askforpassword: YES"
            ;;
        [nN][oO])
            defaults write com.apple.screensaver askForPassword -int 0
            echo "Screensaver askforpassword: NO"
            ;;
        *)
            VALUE=$(defaults read com.apple.screensaver askForPassword)
            if [ "${VALUE}" -eq 1 ]; then
                echo "Screensaver askforpassword: YES"
            else
                echo "Screensaver askforpassword: NO"
            fi
            ;;
    esac
}

status(){
    VALUE=$(osascript -e 'tell application "System Events"' \
        -e 'get running of screen saver preferences' \
        -e 'end tell')
    if [ "${VALUE}" == 'true' ]; then
        echo 'Screensaver is running: YES'
    elif [ "${VALUE}" == 'false' ]; then
        echo 'Screensaver is running: NO'
    else
        echo 'Screensaver is running: ERROR'
    fi
}


case $1 in
    help)
        help
        ;;
    askforpassword)
        shift
        askforpassword $@
        ;;
    status)
        status
        ;;
    *)
        open /System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
