#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/helpers.sh"

help(){
    cat<<__EOF__
    usage: m screensaver [ status | askforpassword | help ]

    Examples:
      m screensaver                         # launch screensaver

      m screensaver status                  #  get the current status
      m screensaver askforpassword          #  get password requirement to unlock
      m screensaver askforpassword YES      #  enable password requirement to unlock
      m screensaver askforpassword NO       #  disable password requirement to unlock
__EOF__
}

askforpassword(){
    local choice="$(_mcli_yes_no_to_integer "$1")"

    defaults write com.apple.screensaver askForPassword -int "${choice}"

    value="$(_mcli_read_boolean "com.apple.screensaver" "askForPassword")"

    echo "Screensaver askforpassword: ${value}"
}

status(){
    local value=$(osascript -e 'tell application "System Events"' \
                            -e 'get running of screen saver preferences' \
                            -e 'end tell')

    value="$(_mcli_yes_no_to_yes_no "${value}")"

    echo "Screensaver is running: ${value}"
}


case $1 in
    help)
        help
        ;;
    askforpassword)
        shift
        askforpassword $@
        ;;
    status)
        status
        ;;
    *)
        open /System/Library/Frameworks/ScreenSaver.framework/Versions/A/Resources/ScreenSaverEngine.app
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
