#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m screencapture type        [             # Specify the type of the screenshots
                                    png  |
                                    jpg  |
                                    tiff |
                                    pdf
                                  ]
      m screencapture location    /path         # The location the screenshots will be saved to
      m screencapture filename                  # The filename the screenshots will be saved under (suffixed by date)
      m screencapture shadow      [ YES | NO ]  # Whether the screenshots will contain a drop shadow

__EOF__
}

type(){
    value="$(_mcli_defaults_string "com.apple.screencapture" \
                                   "type" \
                                   "$1")"

    echo "${command} ${subcommand}: ${value}"
}

location(){
    value="$(_mcli_defaults_string "com.apple.screencapture" \
                                   "location" \
                                   "$1")"

    echo "${command} ${subcommand}: ${value}"
}

filename(){
    value="$(_mcli_defaults_string "com.apple.screencapture" \
                                   "name" \
                                   "$1")"

    echo "${command} ${subcommand}: ${value}"
}

shadow(){
    value="$(_mcli_defaults_string "com.apple.screencapture" \
                                   "disable-shadow" \
                                   "$1")"

    echo "${command} ${subcommand}: ${value}"
}

case "${subcommand}" in
    help)
        help
        ;;
    type)
        type "$@"
        ;;
    location)
        location "$@"
        ;;
    filename)
        filename "$@"
        ;;
    shadow)
        shadow "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
