#!/usr/bin/env bash


help(){
    cat<<__EOF__
Usage: m sleep [--help]

Description: Put the Mac to sleep immediately or after a specified delay

Options:
  --help      Show this help message and exit

Examples:
  m sleep       #  put the mac to sleep
__EOF__
}

case $1 in
    --help)
        help
        ;;
    *)
        pmset sleepnow
        ;;
esac
