#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/keyboard_shortcuts.sh"

help(){
    cat<<__EOF__
    usage: m spotlight [ shortcutkeys | help ]

    Examples:
      m spotlight shortcutkeys [ YES | NO ] # Whether to enable the Cmd-Space shortcuts
__EOF__
}

shortcut_keys() {
    local spotlight_keyboard_shortcut_ids=(64 65)
    local enabled="$(_mcli_convert_yes_no_to_boolean "$1")"

    for keyboard_shortcut_id in "${spotlight_keyboard_shortcut_ids[@]}"; do
        _mcli_keyboard_shortcut_toggle $keyboard_shortcut_id $enabled
    done
}

case $1 in
    help)
        help
        ;;
    shortcutkeys)
        shortcut_keys
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
