#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/keyboard_shortcuts.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m spotlight shortcutkeys [ YES | NO ] # Whether to enable the Cmd-Space shortcuts
__EOF__
}

shortcut_keys() {
    local spotlight_keyboard_shortcut_ids=(64 65)
    local enabled="$(_mcli_convert_yes_no_to_boolean "$1")"

    [ -z "$1" ] && help && return

    for keyboard_shortcut_id in "${spotlight_keyboard_shortcut_ids[@]}"; do
        _mcli_keyboard_shortcut_toggle "${keyboard_shortcut_id}" "${enabled}"
    done

    echo "${command} ${subcommand}: ${enabled}"
}

case "${subcommand}" in
    help)
        help
        ;;
    shortcutkeys)
        shortcut_keys "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
