#!/usr/bin/env bash

help() {
    cat <<__EOF__
usage: m temp [ monitor | help]
__EOF__
}

temp_monitor() {
    sudo powermetrics -i 200 --samplers smc | awk 'BEGIN {  print "Monitoring ..." ; } /CPU die temperature/{ printf "  %s\r", $0 } fflush(stdout)'
}

case $1 in
help)
    help
    ;;
monitor)
    temp_monitor
    ;;
*)
    help
    ;;
esac
