#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/keyboard_shortcuts.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m timemachine usenewdisks          [ YES | NO ]  # Whether to use new disks for backups
      m timemachine useallnetworkvolumes [ YES | NO ]  # Whether to use unsupported network volumes for backups
      m timemachine localbackups         [ YES | NO ]  # Whether to enable local backups
      m timemachine addexclusion         path          # Specify a path to be excluded from backups
__EOF__
}

usenewdisks(){
    value="$(_mcli_defaults_yes_no_to_inverted_boolean "com.apple.TimeMachine" \
                                                       "DoNotOfferNewDisksForBackup" \
                                                       "$1")"

    echo "${command} ${subcommand}: ${value}"
}

useallnetworkvolumes(){
    value="$(_mcli_defaults_yes_no_to_boolean "com.apple.systempreferences" \
                                              "TMShowUnsupportedNetworkVolumes" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

localbackups(){
    value="$(_mcli_convert_yes_no_to_enabled_disabled "$1")"

    sudo tmutil ${value}local
}

addexclusion(){
  sudo defaults write /Library/Preferences/com.apple.TimeMachine SkipPaths -array-add "$1"

  sudo tmutil addexclusion -p "$1"
}

case "${subcommand}" in
    help)
        help
        ;;
    usenewdisks)
        usenewdisks "$@"
        ;;
    useallnetworkvolumes)
        useallnetworkvolumes "$@"
        ;;
    localbackups)
        localbackups "$@"
        ;;
    addexclusion)
        addexclusion "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
