#!/usr/bin/env bash


help(){
    cat<<__EOF__
    Usage:
      m timezone                        # get current timezone
      m timezone ls                     # list available timezones
      m timezone set <time_zone_name>   # set timezone

    Examples:
      m timezone set Europe/Berlin
__EOF__
}


case $1 in
    help)
        help
        ;;
    list|ls)
        sudo systemsetup -listtimezones
        ;;
    set)
        [ -z "$2" ] && help && exit 1;
        sudo systemsetup -settimezone $2
        ;;
    *)
        sudo systemsetup -gettimezone
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
