#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/defaults.sh"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m tooltips delay    x             # Set the delay before the tooltip shows up
      m tooltips autowrap [ YES | NO ]  # Whether tooltips should wrap
      m tooltips fontsize x             # The size of the font in the tooltip
__EOF__
}

delay() {
    value="$(_mcli_defaults_yes_no_to_integer "NSGlobalDomain" \
                                              "NSInitialToolTipDelay" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

autowrap() {
    value="$(_mcli_defaults_yes_no_to_boolean "NSGlobalDomain" \
                                              "NSToolTipAutoWrappingDisabled" \
                                              "$1")"

    echo "${command} ${subcommand}: ${value}"
}

fontsize() {
    value="$(_mcli_defaults_yes_no_to_number "NSGlobalDomain" \
                                             "NSToolTipsFontSize" \
                                             "$1")"

    echo "${command} ${subcommand}: ${value}"
}

fontname() {
    value="$(_mcli_defaults_font "NSGlobalDomain" \
                                 "NSToolTipsFont" \
                                 "$1")"

    echo "${command} ${subcommand}: ${value}"
}

case "${subcommand}" in
    help)
        help
        ;;
    delay)
        delay "$@"
        ;;
    autowrap)
        autowrap "$@"
        ;;
    fontsize)
        fontsize "$@"
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
