#!/usr/bin/env bash

source "$( dirname "${BASH_SOURCE[0]}" )/../lib/converters.sh"
source "$( dirname "${BASH_SOURCE[0]}" )/../lib/keyboard_shortcuts.sh"

help(){
    cat<<__EOF__
    usage: m tooltips [ delay | autowrap | fontsize | fontname | help ]

    Examples:
      m tooltips delay    x             # Set the delay before the tooltip shows up
      m tooltips autowrap [ YES | NO ]  # Whether tooltips should wrap
      m tooltips fontsize x.x           # The size of the font in the tooltip
      m tooltips fontname <font name>   # The name of the font in the tooltip
__EOF__
}

delay() {
    value="$(_mcli_defaults_yes_no_to_integer "NSGlobalDomain" \
                                              "NSInitialToolTipDelay" \
                                              "$1")"

    echo "Keyboard delay: ${value}"
}

autowrap() {
    value="$(_mcli_defaults_yes_no_to_boolean "NSGlobalDomain" \
                                              "NSToolTipAutoWrappingDisabled" \
                                              "$1")"

    echo "Keyboard autowrap: ${value}"
}

fontsize() {
    value="$(_mcli_defaults_yes_no_to_number "NSGlobalDomain" \
                                             "NSToolTipsFontSize" \
                                             "$1")"

    echo "Keyboard fontsize: ${value}"
}

fontname() {
    value="$(_mcli_defaults_font "NSGlobalDomain" \
                                 "NSToolTipsFont" \
                                 "$1")"

    echo "Keyboard fontname: ${value}"
}

case $1 in
    help)
        help
        ;;
    delay)
        delay
        ;;
    autowrap)
        autowrap
        ;;
    fontsize)
        fontsize
        ;;
    fontname)
        fontname
        ;;
    *)
        help
        ;;
esac

# vim: ts=4 sw=4 softtabstop=4 expandtab
