#!/usr/bin/env bash

declare path_to_update_prefs="/Library/Preferences/com.apple.SoftwareUpdate"
declare path_to_appstore_prefs="/Library/Preferences/com.apple.commerce"

declare command="$(basename "$0")"
declare subcommand="$1"

[ $# -gt 0 ] && shift

help(){
    cat<<__EOF__
    Usage:
      m update list                                                           # list available updates
      m update install           [ all | <package_name> ]                     # which updates to install
      m update automaticinstall  [ YES | NO ]                                 # whether automatic installs should be enabled
      m update automaticdownload [ YES | NO ]                                 # whether automatic downloads should be enabled
      m update interval          [ daily | weekly | biweekly | monthly | x ]  # how often to check for updates

    Examples:
      m update install           all                                          # install all the available updates
      m update install           iTunesX-12.4.1 RAWCameraUpdate6.20-6.20      # install specific updates

__EOF__
}

install_updates(){
    # at least one package
    [ -z "$1" ] && help && exit 1
    case $1 in
        all)
            sudo softwareupdate --install --all
            ;;
        *)
            sudo softwareupdate --install "$@"
            ;;
    esac
}

automaticinstall(){
    value="$(_mcli_defaults_yes_no_to_integer "${path_to_update_prefs}" \
                                              "ConfigDataInstall" \
                                              "$1" \
                                              "sudo")"
    value="$(_mcli_defaults_yes_no_to_integer "${path_to_update_prefs}" \
                                              "CriticalUpdateInstall" \
                                              "$1" \
                                              "sudo")"
    value="$(_mcli_defaults_yes_no_to_integer "${path_to_appstore_prefs}" \
                                              "AutoUpdate" \
                                              "$1" \
                                              "sudo")"
    value="$(_mcli_defaults_yes_no_to_integer "${path_to_appstore_prefs}" \
                                              "AutoUpdateRestartRequired" \
                                              "$1" \
                                              "sudo")"

    echo "${command} ${subcommand}: ${value}"
}

automaticdownload(){
    value="$(_mcli_defaults_yes_no_to_integer "${path_to_update_prefs}" \
                                              "AutomaticDownload" \
                                              "$1" \
                                              "sudo")"

    echo "${command} ${subcommand}: ${value}"
}

interval(){
    local interval

    case "$1" in
        daily)
            interval="1";;
        weekly)
            interval="7";;
        biweekly)
            interval="14";;
        monthly)
            interval="30";;
        *)
            interval="$1";;
    esac

    value="$(_mcli_defaults_yes_no_to_integer "${path_to_update_prefs}" \
                                              "ScheduleFrequency" \
                                              "${interval}" \
                                              "sudo")"

    echo "${command} ${subcommand}: ${value}"
}

case $1 in
    help)
        help
        ;;
    list|ls)
        sudo softwareupdate --list
        ;;
    install)
        install_updates "$@"
        ;;
    automaticinstall)
        automaticinstall "$@"
        ;;
    automaticdownload)
        automaticdownload "$@"
        ;;
    interval)
        interval "$@"
        ;;
    *)
        help
        ;;

esac
