#!/usr/bin/env bash

help(){
    cat<<__EOF__
Usage: m usb [OPTION]

Description: List USB devices connected to the system.

Options:
  --help       Show this help message


Example:
      m usb        # list usb devices
__EOF__
}

case $1 in
    --help)
        help
        ;;
    *)
        ioreg -p IOUSB
        ;;
esac
